### ISSUE TITLE
Warning errors

### ISSUE THREAD

**Issue by thomasparsons** [martinandert/react-interpolate-component#4]
carrying on from: https://github.com/martinandert/react-translate-component/issues/21

It would be good to know if this was caused by the interpolate component

thanks

**Comment by martinandert** [comment]
Hi @thomasparsons, I can't really reproduce this. Please add a failing spec to either the translate or interpolate repo, or give a short example which demonstrates the warning you get. Thanks!

**Comment by thomasparsons** [comment]
Sure, I'll try and give you as much as possible:

warning error:

```
app.js:9222 Warning: Unknown prop `stat` on <li> tag. Remove this prop from the element. For details, see https://fb.me/react-unknown-prop
    in li (created by Interpolate)
    in Interpolate (created by Translate)
    in Translate (created by AnalyticsUserOverView)
    in span (created by AnalyticsUserOverView)
    in ul (created by AnalyticsUserOverView)
    in div (created by Section)
    in div (created by Section)
    in Section (created by AnalyticsUserOverView)
    in AnalyticsUserOverView (created by Relay(AnalyticsUserOverView))
    in Relay(AnalyticsUserOverView) (created by Analytics)
    in div (created by Analytics)
    in Analytics (created by Relay(Analytics))
    in Relay(Analytics) (created by AnalyticsPage)
    in div (created by Layout)
    in div (created by Layout)
    in Layout (created by Relay(Layout))
    in Relay(Layout) (created by AnalyticsPage)
    in AnalyticsPage (created by Relay(AnalyticsPage))
    in Relay(AnalyticsPage) (created by RouterContext)
    in StaticContainer (created by RouteContainer)
    in RouteContainer (created by RouterContext)
    in RouterContext (created by Router)
    in ScrollBehaviorContainer (created by Router)
    in StaticContainer (created by RelayReadyStateRenderer)
    in RelayReadyStateRenderer (created by RelayRenderer)
    in RelayRenderer (created by RelayRouterContext)
    in RelayRouterContext (created by Router)
    in Router
```

![screen shot 2016-08-01 at 11 49 39](https://cloud.githubusercontent.com/assets/5320598/17291824/0e4becaa-57de-11e6-9c54-83b5a6739b8b.png)

as you can see In this particular instance I'm passing in a variable called 'stat' which the translation then uses - it looks to me odd, that the variable is then attached to the list element here - could that be the issue - in which case might it be that I caused the error? 

Does that help at all @martinandert

**Comment by martinandert** [comment]
Hi @thomasparsons,

please checkout v0.12.2 of the Translate component. This version introduces a new `with` prop which should now be used for passing interpolations instead of separate props.

Before:

``` jsx
<Translate component="li" content="analytics.overview.properties"  stat={318} unsafe />
```

After:

``` jsx
<Translate component="li" content="analytics.overview.properties" with={{ stat: 318 }} unsafe />
```

Please let me know if that works for you.

**Comment by thomasparsons** [comment]
@martinandert working great, thank you
