### ISSUE TITLE
Component triggers React deprecation warning with React > v15.5.0

### ISSUE THREAD

**Issue by sgehrig** [martinandert/react-interpolate-component#5]
The component triggers a React deprecation warning with React versions greater than v15.5.0:

`Warning: Interpolate: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.`

See https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html for more information.

**Comment by martinandert** [comment]
Fixed in v0.11.
